import type { Cell } from "./subscriptionImport";

/**
 * Columns A–C of the three bracket sheets in Subscriptions.xlsx, verbatim —
 * typos, trailing spaces, blank rows, discount rows and the unlabelled aggregate
 * rows included. Those quirks ARE the parser's contract, so don't tidy them.
 */

export const SHEET_25_30: Cell[][] = [
  ["Item Name", "Protein", "price"],
  ["Moong Daal Soya Keema Wrap", 30, 135],
  ["Soya Keema Hung Curd Sandwich", 27.3, 140],
  ["Paneer Veg Hung Curd Sandwich", 23.8, 160],
  ["Paneer Protein Power Burger", 26.5, 150],
  ["Paneer Salad Bowl (Regular)", 25, 200],
  ["Mexican Veg Burrito Bowl (Regular)", 23.5, 210],
  ["Soya Keema Thali (4 roti)", 30, 170],
  ["Paneer Chana Chaat (Large)", 30, 200],
  ["paneer fried rice (regular)", null, null],
  [null, null, null],
  ["210 - 10% ", null, 170.625],
  ["Final Pricing. - 188", null, null],
  [null, null, null],
  [null, null, null],
  ["Moong Daal Chicken Wrap", 24.7, 160],
  ["Moong Daal Egg Wrap (3egg)", 26, 150],
  ["Chicken Hung Curd Sandwich", 28.9, 180],
  ["Egg Veggie Hung Curd Sandwich", 22.8, 150],
  ["Chicken Protein Power Burger", 23.2, 160],
  ["Egg Protein Power Burger", 25.6, 140],
  ["Butter Chicken Thali (4 roti)", 43.9, 190],
  ["chicken fried rice (regular)", null, null],
  ["Mexican Chicken Burrito Bowl (Regular)", 26.2, 230],
  ["Chcken loaded omellte ", null, 161.4285714],
  [null, null, null],
  ["220 - 10%", null, null],
  ["Final Pricing. - 198", null, null],
];

export const SHEET_30_40: Cell[][] = [
  ["Item Name", "Protein", "price"],
  ["Mexican Veg Burrito Bowl (Large)", 37.4, 300],
  ["Paneer Salad Bowl (Large)", 32.7, 300],
  ["Paneer fried rice (large)", null, 250],
  ["Moong Daal Veggie Wrap + protein shake", 14.5, 230],
  ["Veg Hung Curd Sandwich + protein shake", 16.5, 250],
  ["Veg Protein Burger + protein shake", 19.1, 240],
  ["paneer fried rice (regular) + chach", null, 265],
  ["Butter Paneer Thali (3 roti) + chach", 22.9, 255],
  ["Soya Keema Thali (3 roti) + chach", 40.5, 245],
  [null, null, null],
  ["295 -15%", null, 266],
  ["Final Pricing. - 250", null, null],
  [null, null, null],
  [null, null, null],
  ["Chicken Salad Bowl (Regular)", 33.9, 230],
  ["Moong Daal Chicken Wrap (addon 2 eggs)", 35, 190],
  ["Chicken fried rice (large)", null, 280],
  ["Moong Daal Egg Wrap + chach", 21.1, 225],
  ["Egg Veggie Hung Curd Sandwich + chach", 22.8, 240],
  ["Butter Chicken Thali (3 roti) + chach", 43.9, 265],
  ["chicken fried rice (regular) + chach", null, 290],
  ["Egg fried rice ( regular) + chach", null, 240],
  ["Classic omellete + protein shake ", null, null],
  ["chicken loaded omellete (2 egg addon ) ", null, null],
  [null, null, 231.25], // unlabelled aggregate — must NOT become a nameless item
  ["320 - 15%", null, null],
  ["Final Pricing. - 272", null, null],
];

export const SHEET_40_50: Cell[][] = [
  ["Item Name", "Protein", "price"],
  ["Paneer Caesar Salad (Large) | 45g Protein", 45, 300],
  ["Moong Daal Paneer Wrap + protein shake", 41, 260],
  ["paneer Hung Curd Sandwich + protein shake", 41, 280],
  ["paneer Protein Burger + protein shake", 47, 270],
  ["Soya keema wrap + protein shake ", 47, 255],
  ["Soya keema hung curd sandwich + protein shake ", 47, 260],
  ["Moong dal veggie wrap + mango/vanilla/coffee protein shake ", 45, 270],
  ["veg burger + mango/vanilla/coffee  protein shake ", 45, 280],
  ["betroot paneer burger + mango/vanilla/coffee protein shake ", 40, 310],
  [null, null, null],
  [null, null, null],
  ["375 - 20%", null, 276.1111111],
  ["Final Pricing. - 300", null, null],
  [null, null, null],
  [null, null, null],
  ["Chicken Salad Bowl (Large)", 50, 320],
  ["Mexican Chicken Burrito Bowl (Large)", 42.5, 320],
  ["Angari Chicken", 49.9, 220],
  ["Chicken Protein Power Burger + Protein shake", 42, 280],
  ["Moong Daal Chicken Wrap  + Protein Shake ", 42, 280],
  ["Chicken hung curd sandwich + protein shake ", 47, 300],
  ["Chicken loaded omellete + mango/vanilla/coffee protein shake ", 50, 310],
  [null, null, null],
  [null, null, null],
  [null, null, null],
  [null, null, null],
  [null, null, null],
  [null, null, 290], // unlabelled aggregate
  ["425 - 20%", null, null],
  ["Final Pricing. - 340", null, null],
];
